filter:
  paths: [src/*]
  excluded_paths: [vendor/*, test/*]
before_commands:
  - 'composer update --prefer-source'
checks:
  php: true
coding_style:
  php: {  }
build:
  environment:
    php:
      version: 5.6.9
  tests:
    override:
      -
        command: ./vendor/bin/codecept build -c tests && ./vendor/bin/codecept run acceptance -c tests
